version: "3.3"
services:
  hdfs_master:
    container_name: master
      #build:
      #      context: .
      #      dockerfile: ./DockerFile/HDFS/master
    image: matnar/hadoop
    tty: true
    ports:
      - 9870:9870
      - 54310:54310
    volumes:
      - ./DockerFile/HDFS:/home/data 
    networks:
      - hadoop_network
    depends_on:
      - hdfs_slave1
  hdfs_slave1:
    container_name: slave1
    image: matnar/hadoop
    tty: true
    ports:
      - 9864:9864
    networks:
      - hadoop_network
  nifi:
    container_name: nifi
    hostname: nifi
    image: apache/nifi:latest
    volumes:
      - ./DockerFile/NIFI:/opt/nifi/nifi-current/Data
    ports:
      - 8443:8443
    networks:
      - hadoop_network    
  spark-master:
    container_name: spark_master
    image: cluster-apache-spark:3.0.2
    ports:
      - "9090:8080"
      - "7077:7077"
      - "4040:4040"
      - "18080:18080"
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - hadoop_network
    volumes:
       - ./Spark_scripts:/opt/spark-apps
  spark-worker-a:
    container_name: spark_worker
    image: cluster-apache-spark:3.0.2
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    networks:
      - hadoop_network
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - hadoop_network
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - hadoop_network
  grafana:
    container_name: grafana
    build:
      dockerfile: ./DockerFile/Grafana/Dockerfile 
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: always
    networks:
      - hadoop_network
networks:
  hadoop_network:
    name: hadoop_network
    driver: bridge

