version: '3.9'
services:
  
  hdfs_master:
    hostname: master
    container_name: master_hdfs
    build: 
      context: .
      dockerfile: ./DockerFile/HDFS/master
    tty: true
    ports:
      - 9870:9870
    networks:
      - hadoop_network
    depends_on:
      - hdfs_slave1
      - hdfs_slave2
      - hdfs_slave3
  hdfs_slave1:
    hostname: slave1
    container_name: slave1_hdfs
    image: matnar/hadoop
    tty: true
    ports:
      - 9864:9864
    networks:
      - hadoop_network
  hdfs_slave2:
    hostname: slave2
    container_name: slave2_hdfs
    image: matnar/hadoop
    tty: true
    ports:
      - 9863:9864 
    networks:
      - hadoop_network
  hdfs_slave3:
    hostname: slave3
    container_name: slave3_hdfs
    image: matnar/hadoop
    tty: true
    ports:
      - 9862:9864
    networks:
      - hadoop_network
networks:
  hadoop_network:
    name: hadoop_network
    driver: bridge