version: '3.9'
services:

  hdfs_master:
    container_name: master
    build: 
      context: .
      dockerfile: ./DockerFile/HDFS/master
    tty: true
    ports:
      - 9870:9870
    networks:
      - hadoop_network
    depends_on:
      - hdfs_slave1
      - hdfs_slave2
      - hdfs_slave3
  hdfs_slave1:
    container_name: slave1
    image: matnar/hadoop
    tty: true
    ports:
      - 9864:9864
    networks:
      - hadoop_network
  hdfs_slave2:
    container_name: slave2
    image: matnar/hadoop
    tty: true
    ports:
      - 9863:9864 
    networks:
      - hadoop_network
  hdfs_slave3:
    container_name: slave3
    image: matnar/hadoop
    tty: true
    ports:
      - 9862:9864
    networks:
      - hadoop_network
  nifi:
    hostname: nifi
    container_name: nifi
    build: 
      context: .
      dockerfile: ./DockerFile/NIFI/Dockerfile
    tty: true
    ports:
      - 8443:8443
    networks:
      - hadoop_network    
networks:
  hadoop_network:
    name: hadoop_network
    driver: bridge